### PR TITLE
Language server fixes

### PR DESCRIPTION
**Pull request by jages**
## Description

This merges various changes from @NLueg (originially merged into `openvalidation/openvalidation:develop`) into `openvalidation/openvalidation-rest`, from before the migration to it's own repository.

There are siginificant changes to `pom.xml`, that require various changes.

Due to the changes made to the underlying API this requires [openvalidation PR#57](https://github.com/openvalidation/openvalidation/pull/57) to complete.

### CODE REVIEW

**Comment by jages** [comment]
@thecodemonkey try merging this into master branch, results from maven look good.

**Review by NLueg — DISMISSED** [review]
Looks good to me. I actually don't looked at every file but the implementation works perfectly with the monaco implementation.

**Comment by jages** [comment]
@NLueg why is the port 31057 hard coded into `application.properties`? this is also not reflected in the docker file (resulting in no service from docker). please review.

**Comment by NLueg** [comment]
@jages Well, that's a good point ... I hardcoded the port into `application.properties` because I needed to use a port that is surely not used on the system. This is required for example for the VSCode-Extension, because the backend runs in a separate process and I don't wanted to block a port like `8080`.

But that's a good point with docker. What would you say would be a good solution for this problem? Of course, we just could add the port to docker but maybe you have a better idea for this.

**Comment by jages** [comment]
> @jages Well, that's a good point ... I hardcoded the port into `application.properties` because I needed to use a port that is surely not used on the system. This is required for example for the VSCode-Extension, because the backend runs in a separate process and I don't wanted to block a port like `8080`.
> 
> But that's a good point with docker. What would you say would be a good solution for this problem? Of course, we just could add the port to docker but maybe you have a better idea for this.

all settings in `application.properties` can also be passed as command line arguments.
i will either change the setting in the docker file, or just remove the port from the settings file and adjust the README accordningly. I will request a re-review once i have implemented these changes.

**Comment by jages** [comment]
@NLueg please review the dependency of the specific port in the vs-code and npm package. I currently see no reason to specify the port in the config, as it can just be started in the CLI (especially in the npm package, this could be arranged to start the port with the listening port of the consumer)

**Comment by NLueg** [comment]
@jages I will fix the problem in both packages. But this doesn't block this PR, because the JAR is currently inserted manually in both packages. In my opinion, we can merge this.

**Comment by jages** [comment]
This addresses #2 in a small capacity.

**Pull request merged**
